import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/coverage/**',
      '**/node_modules/**',
      'docs/**',
      // Prisma client output. Regenerated by postinstall, never hand-edited.
      'apps/api/src/generated/**',
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // Server and shared code get type-aware linting. no-floating-promises alone earns
  // the extra seconds in an Express codebase; misused-promises catches the async
  // handler bugs that otherwise surface as a silently hanging request.
  {
    files: ['apps/api/src/**/*.ts', 'packages/contracts/src/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: globals.node,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Express identifies error handlers by arity, so the error middleware must
      // declare `next` whether or not it uses it. Leading underscore = deliberate.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'all' },
      ],
    },
  },

  // The scoped data access layer is only as good as its escape hatch is narrow.
  // `unscopedPrisma` skips district, year and soft-delete filtering entirely, which is
  // correct in exactly three places: the governance module (it resolves the context, so
  // it cannot already hold one), the test fixtures, and the seed. Anywhere else it is a
  // silent breach of axiom 1 that will not look like one in review.
  {
    files: ['apps/api/src/**/*.ts'],
    ignores: [
      'apps/api/src/platform/**',
      'apps/api/src/modules/governance/**',
      'apps/api/src/test/**',
      'apps/api/src/**/*.test.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/platform/db.js', './db.js'],
              importNames: ['unscopedPrisma'],
              message:
                'Use db(ctx) instead. unscopedPrisma skips district, year and soft-delete ' +
                'scoping; it is for context resolution, fixtures and the seed only.',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat['recommended-latest'], reactRefresh.configs.vite],
    languageOptions: {
      globals: globals.browser,
    },
  },

  // Config files run under Node and are not part of any app's tsconfig.
  {
    files: ['**/*.config.{js,ts}', 'eslint.config.js'],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Prettier owns formatting; ESLint must never report it. Keep this last.
  prettier,
);
