import { openDB, type DBSchema, type IDBPDatabase } from 'idb';

/**
 * THE OUTBOX. Every create a club officer makes goes through here, online or not.
 *
 * The rule that makes this correct is that the record is written to IndexedDB **before** any
 * network call is attempted — always, even on a perfect connection. The alternative, "try
 * the network and queue on failure", loses the submission in the one case that matters: the
 * request left the device, the response never came back, and the tab was closed before
 * anything was written down. A secretary in a basement filing three reports must find three.
 *
 * The id is generated by the CLIENT and is the record's id on the server (ADR-004, ADR-006).
 * That is what makes a replay safe, and it is why a 409 here is a SUCCESS rather than an
 * error — see `isAlreadyStored`.
 */

export type OutboxStatus = 'queued' | 'sending' | 'failed';

export interface OutboxItem {
  /** The client-generated UUID. Also the record's id on the server. */
  id: string;
  /** For the pending screen: "Activity" or "Membership event". */
  kind: string;
  /** A one-line summary, so the queue is readable without opening anything. */
  label: string;
  endpoint: string;
  method: 'POST';
  body: Record<string, unknown>;
  /**
   * Photographs, uploaded only AFTER the parent record exists — they are addressed by its
   * id. Stored as Blobs, which IndexedDB holds natively; a base64 string would inflate them
   * by a third on a device already short of space.
   */
  files: Blob[];
  /**
   * Another queued item that must reach the server first.
   *
   * Only one case needs it, but it is a common one: a secretary inducting somebody who is
   * not yet in the system queues the PERSON and then the EVENT that references them. Both
   * ids are client-generated, so the event is valid the moment the person exists — but not
   * one attempt before, and sending it early would earn a `422` and mark it permanently
   * failed for a reason that was only ever about ordering.
   */
  dependsOn: string | null;
  createdAt: number;
  attempts: number;
  lastError: string | null;
  /**
   * The `details` of the last rejection, kept so a validation failure can still land on the
   * control that caused it. The queue turned a synchronous mutation into an asynchronous
   * one; it should not also turn "narrative report is required" into a toast the member has
   * to translate back into a field.
   */
  lastErrorDetails: Record<string, unknown> | null;
  /** When the next attempt is due. Backoff is a timestamp, not a sleeping timer. */
  nextAttemptAt: number;
  status: OutboxStatus;
}

interface OutboxDb extends DBSchema {
  outbox: {
    key: string;
    value: OutboxItem;
    indexes: { 'by-status': OutboxStatus; 'by-created': number };
  };
}

const DB_NAME = 'dis-outbox';
const DB_VERSION = 1;

let dbPromise: Promise<IDBPDatabase<OutboxDb>> | null = null;

function db(): Promise<IDBPDatabase<OutboxDb>> {
  dbPromise ??= openDB<OutboxDb>(DB_NAME, DB_VERSION, {
    upgrade(database) {
      const store = database.createObjectStore('outbox', { keyPath: 'id' });
      store.createIndex('by-status', 'status');
      store.createIndex('by-created', 'createdAt');
    },
  });
  return dbPromise;
}

/**
 * Closes the connection, so tests can delete the database between cases.
 *
 * The close matters: `deleteDB` BLOCKS while any connection is open, so merely dropping the
 * promise would leave the handle alive and hang the next case.
 */
export async function closeOutbox(): Promise<void> {
  const pending = dbPromise;
  dbPromise = null;
  if (pending) (await pending).close();
}

// ─── Reading and writing ─────────────────────────────────────────────────────

/**
 * A strictly increasing timestamp.
 *
 * The queue drains in `createdAt` order, and a member saving three things in quick
 * succession can produce three identical `Date.now()` values — leaving the order of their
 * evening to whatever IndexedDB decides. It also matters for correctness: an item that
 * `dependsOn` another must sort after it.
 */
let lastCreatedAt = 0;

function nextCreatedAt(): number {
  lastCreatedAt = Math.max(Date.now(), lastCreatedAt + 1);
  return lastCreatedAt;
}

export async function enqueue(
  item: Omit<
    OutboxItem,
    | 'createdAt'
    | 'attempts'
    | 'lastError'
    | 'lastErrorDetails'
    | 'status'
    | 'nextAttemptAt'
    | 'dependsOn'
  > & { dependsOn?: string | null },
): Promise<OutboxItem> {
  const record: OutboxItem = {
    ...item,
    dependsOn: item.dependsOn ?? null,
    createdAt: nextCreatedAt(),
    attempts: 0,
    lastError: null,
    lastErrorDetails: null,
    nextAttemptAt: 0,
    status: 'queued',
  };

  await (await db()).put('outbox', record);
  notify();
  return record;
}

export async function allItems(): Promise<OutboxItem[]> {
  const items = await (await db()).getAllFromIndex('outbox', 'by-created');
  return items;
}

export async function pendingCount(): Promise<number> {
  const items = await allItems();
  // `failed` counts too: it is still unsent work, and a badge that hid failures would be a
  // badge that reads zero while three reports sit unfiled.
  return items.length;
}

export async function removeItem(id: string): Promise<void> {
  await (await db()).delete('outbox', id);
  notify();
}

/**
 * Discards an item and everything that depended on it.
 *
 * A membership event naming a person the member has just given up on saving is not work
 * worth keeping: it would go to the server, be refused for a person who does not exist, and
 * come back as a second thing to discard.
 */
export async function discard(id: string): Promise<void> {
  const dependents = (await allItems()).filter((item) => item.dependsOn === id);
  for (const item of dependents) await removeItem(item.id);
  await removeItem(id);
}

async function update(id: string, patch: Partial<OutboxItem>): Promise<void> {
  const database = await db();
  const existing = await database.get('outbox', id);
  if (!existing) return;
  await database.put('outbox', { ...existing, ...patch });
  notify();
}

/**
 * Puts a failed item back in the queue, for the retry button on the pending screen.
 *
 * Anything that depends on it comes back too. A membership event blocked because the person
 * it names could not be saved is not itself broken — it was waiting, and it should go on
 * waiting once the person has another chance.
 */
export async function requeue(id: string): Promise<void> {
  const dependents = (await allItems()).filter((item) => item.dependsOn === id);

  for (const target of [id, ...dependents.map((item) => item.id)]) {
    await update(target, {
      status: 'queued',
      attempts: 0,
      lastError: null,
      lastErrorDetails: null,
      nextAttemptAt: 0,
    });
  }
}

// ─── Subscription, so the badge and the screen stay in step ──────────────────

const listeners = new Set<() => void>();

export function subscribeToOutbox(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function notify(): void {
  for (const listener of listeners) listener();
}

// ─── Draining ────────────────────────────────────────────────────────────────

/** Ten attempts, doubling from 5 seconds and capped at 10 minutes. */
const MAX_ATTEMPTS = 10;
const BASE_BACKOFF_MS = 5_000;
const MAX_BACKOFF_MS = 10 * 60 * 1000;

export function backoffFor(attempts: number): number {
  return Math.min(BASE_BACKOFF_MS * 2 ** Math.max(0, attempts - 1), MAX_BACKOFF_MS);
}

/**
 * Whether the server is telling us this record is ALREADY STORED.
 *
 * `409` is the whole point of client-generated ids: a replay after an ambiguous failure must
 * not create a second record, and the server saying "you already sent this" is the outcome
 * the queue wanted. Treating it as an error would leave the item queued forever, retrying
 * something that has already succeeded.
 *
 * This API answers `200` for a membership event or activity replay and `409
 * IDEMPOTENT_REPLAY` for a club — both mean stored, and the queue does not care which.
 */
function isAlreadyStored(status: number): boolean {
  return status === 409;
}

export interface DrainResult {
  sent: number;
  failed: number;
  /** Everything still in the outbox, including items that need the member. */
  remaining: number;
  /**
   * The subset still worth another attempt.
   *
   * The service worker's `sync` handler rejects on this rather than on `remaining`, which is
   * the difference between "ask me again when there is signal" and an event that retries
   * forever over something only a member can fix.
   */
  pending: number;
}

export interface DrainDeps {
  /** Injected so tests can drive the outcome without a network. */
  send: (item: OutboxItem) => Promise<Response>;
  sendFile: (item: OutboxItem, file: Blob) => Promise<Response>;
  now?: () => number;
}

/**
 * Sends everything that is due.
 *
 * Serial, not parallel. A phone on 3G firing four uploads at once finishes none of them
 * first, and the failure mode of a parallel drain — several items half-sent when the signal
 * drops — is exactly the state this queue exists to avoid.
 */
export async function drainOutbox(deps: DrainDeps): Promise<DrainResult> {
  // One drain at a time. Three things call this — a submission, the interval, and the
  // service worker's sync event — and two overlapping drains would read the same snapshot
  // and send everything twice. The server's idempotency means no duplicate rows, but the
  // second copy is a member's data allowance spent on nothing.
  //
  // A caller that joins a drain already in flight gets a result that predates its own item,
  // so `submit()` reports it as queued. That is the honest answer: it joined a drain of a
  // backlog, and the scheduler will take it within thirty seconds.
  inFlight ??= runDrain(deps).finally(() => {
    inFlight = null;
  });
  return inFlight;
}

let inFlight: Promise<DrainResult> | null = null;

async function runDrain(deps: DrainDeps): Promise<DrainResult> {
  const now = deps.now ?? (() => Date.now());
  const items = await allItems();

  // Updated as the loop goes, so a person sent at the top of this drain unblocks the event
  // that depends on it at the bottom of the SAME drain rather than thirty seconds later.
  const outstanding = new Set(items.map((item) => item.id));

  let sent = 0;
  let failed = 0;

  for (const item of items) {
    if (item.status === 'failed') continue;
    if (item.nextAttemptAt > now()) continue;

    if (item.dependsOn !== null && outstanding.has(item.dependsOn)) {
      // The prerequisite is stuck for good, so this will never be sendable as it stands.
      // Failing it says so; leaving it "Waiting" would show a member a queue that never
      // moves and never explains itself.
      const parent = items.find((other) => other.id === item.dependsOn);
      if (parent?.status === 'failed') {
        await update(item.id, {
          status: 'failed',
          lastError: 'Something it depends on could not be saved.',
        });
        failed += 1;
      }
      // Otherwise the prerequisite has simply not gone yet. An item leaves the outbox the
      // moment the server has it, so absence from `outstanding` is exactly "the parent
      // exists now".
      continue;
    }

    await update(item.id, { status: 'sending' });
    const attempts = item.attempts + 1;

    let response: Response | null = null;
    let networkError: string | null = null;

    try {
      response = await deps.send(item);
    } catch (error) {
      networkError = error instanceof Error ? error.message : 'Network error';
    }

    // No response at all, or the server is unwell. Both are worth trying again.
    if (!response || response.status >= 500) {
      const reason = networkError ?? `Server error ${response?.status ?? ''}`.trim();

      if (attempts >= MAX_ATTEMPTS) {
        await update(item.id, { status: 'failed', attempts, lastError: reason });
        failed += 1;
      } else {
        await update(item.id, {
          status: 'queued',
          attempts,
          lastError: reason,
          nextAttemptAt: now() + backoffFor(attempts),
        });
      }
      continue;
    }

    // 4xx that is not a replay: the request itself is wrong, and sending it again will be
    // wrong in the same way. Surface it for correction rather than burning ten attempts.
    if (!response.ok && !isAlreadyStored(response.status)) {
      const { message, details } = await readError(response);
      await update(item.id, {
        status: 'failed',
        attempts,
        lastError: message,
        lastErrorDetails: details,
      });
      failed += 1;
      continue;
    }

    // Stored — whether it was created now or had been created by an earlier attempt whose
    // response never arrived. Photographs go up afterwards, because they are addressed by
    // the parent's id.
    for (const file of item.files) {
      // A photograph that fails is not worth failing the report for: the activity is filed,
      // and an image can be added again from the detail screen.
      await deps.sendFile(item, file).catch(() => undefined);
    }

    await removeItem(item.id);
    outstanding.delete(item.id);
    sent += 1;
  }

  const left = await allItems();
  return {
    sent,
    failed,
    remaining: left.length,
    pending: left.filter((item) => item.status !== 'failed').length,
  };
}

async function readError(
  response: Response,
): Promise<{ message: string; details: Record<string, unknown> | null }> {
  const fallback = `Request failed (${response.status})`;
  try {
    const body: unknown = await response.json();
    const error = (
      body as { error?: { message?: string; details?: Record<string, unknown> } } | null
    )?.error;
    return { message: error?.message ?? fallback, details: error?.details ?? null };
  } catch {
    return { message: fallback, details: null };
  }
}
